version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build and debloy:
    docker:
      - image: "cimg/base:stable"
    steps:
                # preparing circleci environement
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
                # installing frontend dependencies
          name: Front-End Install
          command: |
            yarn frontend:install
            
               
      
      - run:
                # installing backend dependencies
          name: Back-End Install
          command: |
            yarn backend:install
      - run:
               # buidling frontend production code
          name: Front-End Build
          command: |
            yarn frontend:build
      - run:
              # buidling backend production code
          name: Back-End Build
          command: |
            yarn backend:build
      - run:
              # deploying production frontend code to s3 bucket
          name: Deploy Frontend
          command: |
            yarn frontend:deploy
      - run:
              # deploying production backend code to elasticbeanstalk
          name: Deploy Backend
          command: |
            yarn backend:deploy
