version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
          name: Front-End Install
          command: |
            yarn frontend:install
      - run:
          name: Back-End Install
          command: |
            yarn backend:install
      - run:
          name: Front-End Build
          command: |
            yarn frontend:build
      - run:
          name: Back-End Build
          command: |
            yarn backend:build
      - run:
          name: Deploy Frontend
          command: |
            yarn frontend:deploy
      - run:
          name: Deploy Backend
          command: |
            yarn backend:deploy